import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { auth } from "@/auth";
import SignInButton from "@/components/signInButton";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center justify-between gap-4 px-6 py-8">
          <Link href="/">
            <Image
              src="/logo-colored.svg"
              alt="Kompe logo"
              width={144}
              height={38}
              priority
            />
          </Link>
          {session ? (
            <Avatar>
              <AvatarImage src={session.user?.avatar_url || undefined} />
              <AvatarFallback>
                {session.user?.display_name?.split("", 2)}
              </AvatarFallback>
            </Avatar>
          ) : (
            <SignInButton variant="minimal" />
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
