export const CONTEST_CATEGORIES = [
  { id: "fashion", label: "アパレル・ファッション" },
  { id: "beauty", label: "美容・コスメ" },
  { id: "health", label: "ヘルス・フィットネス" },
  { id: "music", label: "音楽" },
  { id: "game", label: "ゲーム" },
  { id: "sports", label: "スポーツ・アウトドア" },
  { id: "technology", label: "テクノロジー" },
  { id: "hobby", label: "ホビー・エンタメ" },
  { id: "business", label: "ビジネス" },
  { id: "food", label: "フード・グルメ" },
  { id: "pet", label: "ペット" },
  { id: "hotel", label: "ホテル・旅行" },
  { id: "other", label: "その他" },
];
